
services:
  db:
    build: ./DB
    ports:
      - "5435:${DB_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  backend:
    build: ./Backend      
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"   
    depends_on:
      - db                
    environment:
      DB_HOST: db         
      DB_PORT: ${DB_PORT}      
      DB_USER: ${POSTGRES_USER}  
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      PORT: ${BACKEND_PORT}          


volumes:
  pgdata: