
services:
  db:
    build: ./DB
    ports:
      - "5435:${DB_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - docker_network
      
  backend:
    build: ./Backend      
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"   
    depends_on:
      - db                
    environment:
      DB_HOST: db         
      DB_PORT: ${DB_PORT}      
      DB_USER: ${POSTGRES_USER}  
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB} 
      PORT: ${BACKEND_PORT}       
    networks:
      - docker_network   

  frontend:
    build:
      context: ./Frontend
    environment:
      REACT_APP_BACKEND_URL: "http://backend:${BACKEND_PORT}" 
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - docker_network
    
  pinger:
    build:
      context: ./pinger
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:${BACKEND_PORT}"    
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge

volumes:
  pgdata: